---
codecov:
  branch: master
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 0
  round: down
  range: "70...100"
  status:
    project:
      default:
        enabled: yes
        threshold: 5%
    patch:
      default:
        enabled: yes
        threshold: 5%
    changes: no

comment: false

ignore:
- "**/espresso/build/src/python/espressomd/"
