exclude: '.git|.tox'
default_stages: [pre-commit]
fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      # Run the Ruff linter (replaces flake8 and isort)
      - id: ruff
        args: [ --fix ]
      # Run the Ruff formatter (replaces black)
      - id: ruff-format