# This workflow will install Python dependencies and run code coverage analysis.

name: coverage

on:
  push:
  schedule:
    - cron: '14 3 * * 1'  # at 03:14 on Monday.

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: 
        - "3.10"

    steps:
      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls